name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: run eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
      - run: npm run lint
  tsc:
    runs-on: ubuntu-latest
    name: run typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install
      - run: npm run tsc
